@url = http://localhost:4000

### PROJECTS TEST

### GET TEST
GET {{url}}/api/projects

### GET BY ID TEST
GET {{url}}/api/projects/1

### POST TEST
POST {{url}}/api/projects
Content-Type: application/json

{
    "name": "NEW PROJECT",
    "description": "something"
}

### POST TEST MISSING DATA
POST {{url}}/api/projects
Content-Type: application/json

{
    "description": "something"
}

### PUT TEST
PUT {{url}}/api/projects/2
Content-Type: application/json

{
    "name": "UPDATED PROJECT",
    "description": "Project has been updated"
}

### PUT TEST INVALID ID
PUT {{url}}/api/projects/10100101
Content-Type: application/json

{
    "name": "al;skdjf;alsjf PROJECT",
    "description": "Project has been updated"
}

### DELETE TEST
DELETE {{url}}/api/projects/3

### GET PROJECT ACTIONS
GET {{url}}/api/projects/1/actions

### ACTIONS TEST

### GET TEST
GET {{url}}/api/actions

### GET BY ID TEST
GET {{url}}/api/actions/2

### POST TEST
POST {{url}}/api/actions/2
Content-Type: application/json

{
    "description": "STUFF IN HERE",
    "notes": "Information"
}